export const database = {
  id: "orkestria",
  name: "OrkestriaAI",
};

const text = (key, size, required = true, extra = {}) => ({
  key,
  type: "string",
  size,
  required,
  ...extra,
});

const integer = (key, required = true, extra = {}) => ({
  key,
  type: "integer",
  required,
  ...extra,
});

const datetime = (key, required = true) => ({
  key,
  type: "datetime",
  required,
});

export const tables = [
  {
    id: "workspaces",
    name: "Workspaces",
    rowSecurity: true,
    columns: [
      text("name", 128),
      text("slug", 64),
      text("plan", 32, false, { default: "starter" }),
      text("region", 32, false, { default: "global" }),
      text("status", 32, false, { default: "active" }),
      text("settings", 16384, false, { default: "{}" }),
      text("createdBy", 254),
      datetime("createdAt"),
    ],
    indexes: [
      { key: "slug_unique", type: "unique", attributes: ["slug"] },
      { key: "created_by_idx", type: "key", attributes: ["createdBy"] },
    ],
  },
  {
    id: "memberships",
    name: "Memberships",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("userId", 36),
      text("userEmail", 254),
      text("userName", 128, false),
      text("role", 32),
      text("teamId", 36, false),
      text("status", 32, false, { default: "active" }),
      datetime("createdAt"),
    ],
    indexes: [
      {
        key: "workspace_user_unique",
        type: "unique",
        attributes: ["workspaceId", "userEmail"],
      },
      { key: "user_email_idx", type: "key", attributes: ["userEmail"] },
      { key: "user_id_idx", type: "key", attributes: ["userId"] },
      { key: "workspace_role_idx", type: "key", attributes: ["workspaceId", "role"] },
    ],
  },
  {
    id: "runs",
    name: "Agent runs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("agent", 32),
      text("title", 255),
      text("status", 32),
      text("risk", 32),
      text("initiatorEmail", 254),
      text("currentStep", 255, false),
      integer("progress", false, { default: 0 }),
      integer("costCents", false, { default: 0 }),
      datetime("startedAt"),
      datetime("completedAt", false),
      text("metadata", 16384, false, { default: "{}" }),
    ],
    indexes: [
      { key: "workspace_status_idx", type: "key", attributes: ["workspaceId", "status"] },
      { key: "workspace_started_idx", type: "key", attributes: ["workspaceId", "startedAt"], orders: ["ASC", "DESC"] },
    ],
  },
  {
    id: "approvals",
    name: "Approval requests",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("runId", 36),
      text("action", 255),
      text("description", 4000),
      text("risk", 32),
      text("state", 32, false, { default: "pending" }),
      text("requestedBy", 254),
      text("approverEmail", 254, false),
      text("reason", 2000, false),
      datetime("requestedAt"),
      datetime("decidedAt", false),
    ],
    indexes: [
      { key: "workspace_state_idx", type: "key", attributes: ["workspaceId", "state"] },
      { key: "run_id_idx", type: "key", attributes: ["runId"] },
    ],
  },
  {
    id: "audit_events",
    name: "Audit events",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("actorEmail", 254),
      text("action", 128),
      text("targetType", 64),
      text("targetId", 36),
      text("outcome", 32),
      text("ipHash", 64, false),
      text("metadata", 16384, false, { default: "{}" }),
      datetime("occurredAt"),
    ],
    indexes: [
      { key: "workspace_time_idx", type: "key", attributes: ["workspaceId", "occurredAt"], orders: ["ASC", "DESC"] },
      { key: "target_idx", type: "key", attributes: ["targetType", "targetId"] },
    ],
  },
  {
    id: "jobs",
    name: "Background jobs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("type", 64),
      text("payload", 16384, false, { default: "{}" }),
      text("state", 32, false, { default: "queued" }),
      integer("attempts", false, { default: 0 }),
      integer("maxAttempts", false, { default: 5 }),
      text("idempotencyKey", 128),
      datetime("availableAt"),
      datetime("leaseUntil", false),
      text("lastError", 4000, false),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "idempotency_unique", type: "unique", attributes: ["idempotencyKey"] },
      { key: "queue_idx", type: "key", attributes: ["state", "availableAt"] },
      { key: "workspace_state_idx", type: "key", attributes: ["workspaceId", "state"] },
    ],
  },
  {
    id: "files",
    name: "File metadata",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("bucketId", 36),
      text("fileId", 36),
      text("ownerEmail", 254),
      text("name", 255),
      text("mimeType", 128),
      integer("size"),
      text("scanStatus", 32, false, { default: "pending" }),
      datetime("retentionUntil", false),
      datetime("createdAt"),
    ],
    indexes: [
      { key: "file_unique", type: "unique", attributes: ["bucketId", "fileId"] },
      { key: "workspace_owner_idx", type: "key", attributes: ["workspaceId", "ownerEmail"] },
    ],
  },
  {
    id: "rate_limits",
    name: "Rate limits",
    rowSecurity: false,
    columns: [
      text("scope", 128),
      datetime("windowStart"),
      integer("count", false, { default: 0 }),
      integer("limit"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "scope_window_unique", type: "unique", attributes: ["scope", "windowStart"] },
    ],
  },
  {
    id: "cost_analyses",
    name: "Cloud cost analyses",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("runId", 36),
      text("provider", 32),
      text("billingPeriod", 32),
      text("currency", 8, false, { default: "USD" }),
      integer("currentSpendCents", false, { default: 0 }),
      integer("forecastSpendCents", false, { default: 0 }),
      integer("potentialSavingsCents", false, { default: 0 }),
      integer("anomalyCount", false, { default: 0 }),
      integer("opportunityCount", false, { default: 0 }),
      text("metadata", 16384, false, { default: "{}" }),
      datetime("createdAt"),
    ],
    indexes: [
      { key: "run_unique", type: "unique", attributes: ["runId"] },
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
    ],
  },
  {
    id: "savings_opportunities",
    name: "Savings opportunities",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("analysisId", 36),
      text("runId", 36),
      text("resourceId", 255),
      text("resourceName", 255),
      text("category", 64),
      text("status", 32, false, { default: "proposed" }),
      text("risk", 32),
      text("effort", 32),
      integer("confidence", false, { default: 0 }),
      integer("currentMonthlyCostCents", false, { default: 0 }),
      integer("estimatedMonthlySavingsCents", false, { default: 0 }),
      integer("realizedSavingsCents", false, { default: 0 }),
      text("evidence", 4000),
      text("recommendation", 4000),
      datetime("createdAt"),
      datetime("verifiedAt", false),
    ],
    indexes: [
      { key: "analysis_idx", type: "key", attributes: ["analysisId"] },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
      { key: "run_idx", type: "key", attributes: ["runId"] },
    ],
  },
  {
    id: "enterprise_configs",
    name: "Enterprise configurations",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("identityMode", 32, false, { default: "saml_ready" }),
      text("primaryDomain", 254, false),
      text("domainStatus", 32, false, { default: "pending_verification" }),
      text("scimStatus", 32, false, { default: "not_connected" }),
      datetime("lastScimSyncAt", false),
      text("dataRegion", 32, false, { default: "eu-west" }),
      text("residencyMode", 32, false, { default: "pinned" }),
      text("privateNetworkStatus", 32, false, { default: "not_connected" }),
      text("privateNetworkProvider", 64, false, { default: "cloudflare_access" }),
      text("slaTier", 32, false, { default: "enterprise_99_95" }),
      text("supportStatus", 32, false, { default: "ready" }),
      text("settings", 16384, false, { default: "{}" }),
      text("updatedBy", 254),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "region_idx", type: "key", attributes: ["dataRegion"] },
    ],
  },
  {
    id: "custom_roles",
    name: "Custom roles",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 64),
      text("description", 255),
      text("capabilities", 4096, false, { default: "[]" }),
      text("status", 32, false, { default: "active" }),
      integer("memberCount", false, { default: 0 }),
      text("createdBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_name_unique",
        type: "unique",
        attributes: ["workspaceId", "name"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "policy_packs",
    name: "Policy packs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 96),
      text("framework", 64),
      text("version", 32),
      text("mode", 32, false, { default: "monitor" }),
      text("status", 32, false, { default: "active" }),
      integer("rulesCount", false, { default: 0 }),
      integer("coverage", false, { default: 0 }),
      text("content", 16384, false, { default: "{}" }),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_framework_idx",
        type: "key",
        attributes: ["workspaceId", "framework"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "compliance_exports",
    name: "Compliance exports",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("framework", 64),
      text("format", 16, false, { default: "json" }),
      text("status", 32, false, { default: "queued" }),
      text("period", 64),
      text("checksum", 64, false),
      text("requestedBy", 254),
      datetime("createdAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
];

export const buckets = [
  {
    id: "workspace-uploads",
    name: "Workspace uploads",
    fileSecurity: true,
    maximumFileSize: 50 * 1024 * 1024,
    allowedFileExtensions: [
      "pdf", "docx", "txt", "csv", "json", "log", "yaml", "yml",
      "tf", "js", "jsx", "ts", "tsx", "py", "go", "java", "rb",
      "php", "sh", "xml", "toml", "ini", "conf", "png", "jpg", "jpeg",
    ],
  },
  {
    id: "run-evidence",
    name: "Run evidence",
    fileSecurity: true,
    maximumFileSize: 100 * 1024 * 1024,
    allowedFileExtensions: ["json", "txt", "log", "png", "jpg", "jpeg", "pdf"],
  },
  {
    id: "exports",
    name: "Generated exports",
    fileSecurity: true,
    maximumFileSize: 250 * 1024 * 1024,
    allowedFileExtensions: ["csv", "json", "pdf", "zip"],
  },
];

export const functionDefinition = {
  id: "orchestrator",
  name: "Orkestria Orchestrator",
  runtime: "node-22",
  entrypoint: "src/main.js",
  commands: "npm install",
  timeout: 120,
  scopes: [
    "databases.read",
    "databases.write",
    "rows.read",
    "rows.write",
    "buckets.read",
    "buckets.write",
    "files.read",
    "files.write",
  ],
};
