export const database = {
  id: "orkestria",
  name: "OrkestriaAI",
};

const text = (key, size, required = true, extra = {}) => ({
  key,
  type: "string",
  size,
  required,
  ...extra,
});

const integer = (key, required = true, extra = {}) => ({
  key,
  type: "integer",
  required,
  ...extra,
});

const datetime = (key, required = true) => ({
  key,
  type: "datetime",
  required,
});

export const tables = [
  {
    id: "workspaces",
    name: "Workspaces",
    rowSecurity: true,
    columns: [
      text("name", 128),
      text("slug", 64),
      text("plan", 32, false, { default: "starter" }),
      text("region", 32, false, { default: "global" }),
      text("status", 32, false, { default: "active" }),
      text("settings", 16384, false, { default: "{}" }),
      text("createdBy", 254),
      datetime("createdAt"),
    ],
    indexes: [
      { key: "slug_unique", type: "unique", attributes: ["slug"] },
      { key: "created_by_idx", type: "key", attributes: ["createdBy"] },
    ],
  },
  {
    id: "memberships",
    name: "Memberships",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("userId", 36),
      text("userEmail", 254),
      text("userName", 128, false),
      text("role", 32),
      text("teamId", 36, false),
      text("status", 32, false, { default: "active" }),
      datetime("createdAt"),
    ],
    indexes: [
      {
        key: "workspace_user_unique",
        type: "unique",
        attributes: ["workspaceId", "userEmail"],
      },
      { key: "user_email_idx", type: "key", attributes: ["userEmail"] },
      { key: "user_id_idx", type: "key", attributes: ["userId"] },
      { key: "workspace_role_idx", type: "key", attributes: ["workspaceId", "role"] },
    ],
  },
  {
    id: "runs",
    name: "Agent runs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("agent", 32),
      text("title", 255),
      text("status", 32),
      text("risk", 32),
      text("initiatorEmail", 254),
      text("currentStep", 255, false),
      integer("progress", false, { default: 0 }),
      integer("costCents", false, { default: 0 }),
      datetime("startedAt"),
      datetime("completedAt", false),
      text("metadata", 16384, false, { default: "{}" }),
    ],
    indexes: [
      { key: "workspace_status_idx", type: "key", attributes: ["workspaceId", "status"] },
      { key: "workspace_started_idx", type: "key", attributes: ["workspaceId", "startedAt"], orders: ["ASC", "DESC"] },
    ],
  },
  {
    id: "approvals",
    name: "Approval requests",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("runId", 36),
      text("action", 255),
      text("description", 4000),
      text("risk", 32),
      text("state", 32, false, { default: "pending" }),
      text("requestedBy", 254),
      text("approverEmail", 254, false),
      text("reason", 2000, false),
      datetime("requestedAt"),
      datetime("decidedAt", false),
    ],
    indexes: [
      { key: "workspace_state_idx", type: "key", attributes: ["workspaceId", "state"] },
      { key: "run_id_idx", type: "key", attributes: ["runId"] },
    ],
  },
  {
    id: "audit_events",
    name: "Audit events",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("actorEmail", 254),
      text("action", 128),
      text("targetType", 64),
      text("targetId", 36),
      text("outcome", 32),
      text("ipHash", 64, false),
      text("metadata", 16384, false, { default: "{}" }),
      datetime("occurredAt"),
    ],
    indexes: [
      { key: "workspace_time_idx", type: "key", attributes: ["workspaceId", "occurredAt"], orders: ["ASC", "DESC"] },
      { key: "target_idx", type: "key", attributes: ["targetType", "targetId"] },
    ],
  },
  {
    id: "jobs",
    name: "Background jobs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("type", 64),
      text("payload", 16384, false, { default: "{}" }),
      text("state", 32, false, { default: "queued" }),
      integer("attempts", false, { default: 0 }),
      integer("maxAttempts", false, { default: 5 }),
      text("idempotencyKey", 128),
      datetime("availableAt"),
      datetime("leaseUntil", false),
      text("lastError", 4000, false),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "idempotency_unique", type: "unique", attributes: ["idempotencyKey"] },
      { key: "queue_idx", type: "key", attributes: ["state", "availableAt"] },
      { key: "workspace_state_idx", type: "key", attributes: ["workspaceId", "state"] },
    ],
  },
  {
    id: "files",
    name: "File metadata",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("bucketId", 36),
      text("fileId", 36),
      text("ownerEmail", 254),
      text("name", 255),
      text("mimeType", 128),
      integer("size"),
      text("scanStatus", 32, false, { default: "pending" }),
      datetime("retentionUntil", false),
      datetime("createdAt"),
    ],
    indexes: [
      { key: "file_unique", type: "unique", attributes: ["bucketId", "fileId"] },
      { key: "workspace_owner_idx", type: "key", attributes: ["workspaceId", "ownerEmail"] },
    ],
  },
  {
    id: "rate_limits",
    name: "Rate limits",
    rowSecurity: false,
    columns: [
      text("scope", 128),
      datetime("windowStart"),
      integer("count", false, { default: 0 }),
      integer("limit"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "scope_window_unique", type: "unique", attributes: ["scope", "windowStart"] },
    ],
  },
  {
    id: "cost_analyses",
    name: "Cloud cost analyses",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("runId", 36),
      text("provider", 32),
      text("billingPeriod", 32),
      text("currency", 8, false, { default: "USD" }),
      integer("currentSpendCents", false, { default: 0 }),
      integer("forecastSpendCents", false, { default: 0 }),
      integer("potentialSavingsCents", false, { default: 0 }),
      integer("anomalyCount", false, { default: 0 }),
      integer("opportunityCount", false, { default: 0 }),
      text("metadata", 16384, false, { default: "{}" }),
      datetime("createdAt"),
    ],
    indexes: [
      { key: "run_unique", type: "unique", attributes: ["runId"] },
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
    ],
  },
  {
    id: "savings_opportunities",
    name: "Savings opportunities",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("analysisId", 36),
      text("runId", 36),
      text("resourceId", 255),
      text("resourceName", 255),
      text("category", 64),
      text("status", 32, false, { default: "proposed" }),
      text("risk", 32),
      text("effort", 32),
      integer("confidence", false, { default: 0 }),
      integer("currentMonthlyCostCents", false, { default: 0 }),
      integer("estimatedMonthlySavingsCents", false, { default: 0 }),
      integer("realizedSavingsCents", false, { default: 0 }),
      text("evidence", 4000),
      text("recommendation", 4000),
      datetime("createdAt"),
      datetime("verifiedAt", false),
    ],
    indexes: [
      { key: "analysis_idx", type: "key", attributes: ["analysisId"] },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
      { key: "run_idx", type: "key", attributes: ["runId"] },
    ],
  },
  {
    id: "enterprise_configs",
    name: "Enterprise configurations",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("identityMode", 32, false, { default: "saml_ready" }),
      text("primaryDomain", 254, false),
      text("domainStatus", 32, false, { default: "pending_verification" }),
      text("scimStatus", 32, false, { default: "not_connected" }),
      datetime("lastScimSyncAt", false),
      text("dataRegion", 32, false, { default: "eu-west" }),
      text("residencyMode", 32, false, { default: "pinned" }),
      text("privateNetworkStatus", 32, false, { default: "not_connected" }),
      text("privateNetworkProvider", 64, false, { default: "cloudflare_access" }),
      text("slaTier", 32, false, { default: "enterprise_99_95" }),
      text("supportStatus", 32, false, { default: "ready" }),
      text("settings", 16384, false, { default: "{}" }),
      text("updatedBy", 254),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "region_idx", type: "key", attributes: ["dataRegion"] },
    ],
  },
  {
    id: "custom_roles",
    name: "Custom roles",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 64),
      text("description", 255),
      text("capabilities", 4096, false, { default: "[]" }),
      text("status", 32, false, { default: "active" }),
      integer("memberCount", false, { default: 0 }),
      text("createdBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_name_unique",
        type: "unique",
        attributes: ["workspaceId", "name"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "policy_packs",
    name: "Policy packs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 96),
      text("framework", 64),
      text("version", 32),
      text("mode", 32, false, { default: "monitor" }),
      text("status", 32, false, { default: "active" }),
      integer("rulesCount", false, { default: 0 }),
      integer("coverage", false, { default: 0 }),
      text("content", 16384, false, { default: "{}" }),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_framework_idx",
        type: "key",
        attributes: ["workspaceId", "framework"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "compliance_exports",
    name: "Compliance exports",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("framework", 64),
      text("format", 16, false, { default: "json" }),
      text("status", 32, false, { default: "queued" }),
      text("period", 64),
      text("checksum", 64, false),
      text("requestedBy", 254),
      datetime("createdAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "connector_catalog",
    name: "Connector catalog",
    rowSecurity: false,
    columns: [
      text("slug", 64),
      text("name", 96),
      text("category", 64),
      text("description", 255),
      text("publisher", 96),
      text("publisherType", 32, false, { default: "verified" }),
      text("authType", 64),
      text("version", 32),
      text("status", 32, false, { default: "available" }),
      text("capabilities", 8192, false, { default: "[]" }),
      text("agentKeys", 1024, false, { default: "[]" }),
      integer("actionsCount", false, { default: 0 }),
      integer("featured", false, { default: 0 }),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "slug_unique", type: "unique", attributes: ["slug"] },
      { key: "category_status_idx", type: "key", attributes: ["category", "status"] },
      { key: "featured_idx", type: "key", attributes: ["featured"] },
    ],
  },
  {
    id: "connector_installations",
    name: "Connector installations",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("connectorId", 36),
      text("connectorSlug", 64),
      text("status", 32, false, { default: "configuration_required" }),
      text("authStatus", 32, false, { default: "not_authorized" }),
      text("environment", 32, false, { default: "production" }),
      text("installedBy", 254),
      text("config", 8192, false, { default: "{}" }),
      datetime("installedAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_connector_unique",
        type: "unique",
        attributes: ["workspaceId", "connectorId"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "policy_templates",
    name: "Vertical policy templates",
    rowSecurity: false,
    columns: [
      text("slug", 64),
      text("name", 96),
      text("industry", 64),
      text("description", 255),
      text("framework", 64),
      text("version", 32),
      integer("rulesCount", false, { default: 0 }),
      text("content", 16384, false, { default: "{}" }),
      text("status", 32, false, { default: "available" }),
      integer("featured", false, { default: 0 }),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "slug_unique", type: "unique", attributes: ["slug"] },
      { key: "industry_status_idx", type: "key", attributes: ["industry", "status"] },
    ],
  },
  {
    id: "product_signals",
    name: "Product intelligence signals",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("source", 64),
      text("kind", 64),
      text("title", 180),
      text("description", 1000),
      text("status", 32, false, { default: "open" }),
      text("priority", 32, false, { default: "medium" }),
      integer("score", false, { default: 0 }),
      text("evidence", 2000),
      text("recommendation", 2000),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
    ],
  },
  {
    id: "partner_submissions",
    name: "Partner connector submissions",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 96),
      text("connectorSlug", 64),
      text("manifest", 16384),
      text("status", 32, false, { default: "validated_draft" }),
      text("validation", 4096, false, { default: "{}" }),
      text("submittedBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_slug_unique",
        type: "unique",
        attributes: ["workspaceId", "connectorSlug"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "provider_authorizations",
    name: "Provider authorizations",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("installationId", 36),
      text("provider", 64),
      text("authType", 64),
      text("state", 32, false, { default: "awaiting_credentials" }),
      text("scopes", 4096, false, { default: "[]" }),
      text("secretRef", 255, false),
      datetime("expiresAt", false),
      datetime("lastCheckedAt", false),
      text("authorizedBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_installation_unique",
        type: "unique",
        attributes: ["workspaceId", "installationId"],
      },
      {
        key: "workspace_state_idx",
        type: "key",
        attributes: ["workspaceId", "state"],
      },
    ],
  },
  {
    id: "usage_ledger",
    name: "Usage ledger",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("meter", 64),
      integer("quantity"),
      text("unit", 32),
      text("sourceType", 64),
      text("sourceId", 36),
      text("period", 32),
      integer("costCents", false, { default: 0 }),
      text("idempotencyKey", 128),
      datetime("recordedAt"),
    ],
    indexes: [
      { key: "idempotency_unique", type: "unique", attributes: ["idempotencyKey"] },
      {
        key: "workspace_period_idx",
        type: "key",
        attributes: ["workspaceId", "period"],
      },
      {
        key: "workspace_time_idx",
        type: "key",
        attributes: ["workspaceId", "recordedAt"],
        orders: ["ASC", "DESC"],
      },
    ],
  },
  {
    id: "recovery_drills",
    name: "Recovery drills",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("kind", 64),
      text("status", 32),
      text("scope", 255),
      integer("rpoMinutes"),
      integer("rtoMinutes"),
      text("evidence", 8192, false, { default: "{}" }),
      text("initiatedBy", 254),
      datetime("startedAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_started_idx",
        type: "key",
        attributes: ["workspaceId", "startedAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "validation_runs",
    name: "Production validation runs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("jobId", 36),
      text("suite", 64),
      text("status", 32),
      integer("score", false, { default: 0 }),
      text("checks", 16384, false, { default: "[]" }),
      text("initiatedBy", 254),
      datetime("startedAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      { key: "job_unique", type: "unique", attributes: ["jobId"] },
      {
        key: "workspace_started_idx",
        type: "key",
        attributes: ["workspaceId", "startedAt"],
        orders: ["ASC", "DESC"],
      },
    ],
  },
  {
    id: "pilot_programs",
    name: "Pilot programs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 96),
      text("stage", 32, false, { default: "readiness" }),
      text("status", 32, false, { default: "preparing" }),
      integer("targetUsers", false, { default: 10 }),
      text("ownerEmail", 254),
      text("successCriteria", 4096, false, { default: "[]" }),
      text("checklist", 8192, false, { default: "{}" }),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "status_idx", type: "key", attributes: ["status"] },
    ],
  },
  {
    id: "pilot_members",
    name: "Pilot members",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("pilotId", 36),
      text("email", 254),
      text("role", 32, false, { default: "participant" }),
      text("status", 32, false, { default: "proposed" }),
      text("invitationState", 32, false, { default: "draft_not_sent" }),
      text("consentState", 32, false, { default: "not_requested" }),
      datetime("lastActiveAt", false),
      text("invitedBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_email_unique",
        type: "unique",
        attributes: ["workspaceId", "email"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "action_scopes",
    name: "Production action scopes",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 96),
      text("provider", 64),
      text("environment", 32, false, { default: "production" }),
      text("action", 128),
      text("risk", 32),
      integer("approvalRequired", false, { default: 1 }),
      text("status", 32, false, { default: "draft" }),
      text("constraints", 8192, false, { default: "{}" }),
      text("createdBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_action_unique",
        type: "unique",
        attributes: ["workspaceId", "action"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "pilot_exercises",
    name: "Pilot action exercises",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("pilotId", 36),
      text("scopeId", 36),
      text("providerAuthorizationId", 36, false),
      text("approvalId", 36, false),
      text("state", 32),
      text("outcome", 64),
      integer("externalActionExecuted", false, { default: 0 }),
      text("evidence", 8192, false, { default: "{}" }),
      text("initiatedBy", 254),
      datetime("startedAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_started_idx",
        type: "key",
        attributes: ["workspaceId", "startedAt"],
        orders: ["ASC", "DESC"],
      },
      { key: "scope_idx", type: "key", attributes: ["scopeId"] },
    ],
  },
  {
    id: "support_rotations",
    name: "Pilot support rotations",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 96),
      text("status", 32, false, { default: "partial" }),
      text("timezone", 64, false, { default: "UTC" }),
      text("primaryEmail", 254),
      text("secondaryEmail", 254, false),
      text("coverage", 64, false, { default: "business_hours" }),
      text("escalationPolicy", 8192, false, { default: "{}" }),
      datetime("lastHandoffAt", false),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "status_idx", type: "key", attributes: ["status"] },
    ],
  },
  {
    id: "launch_decisions",
    name: "Launch decisions",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("status", 32, false, { default: "assessing" }),
      text("recommendation", 32, false, { default: "hold" }),
      integer("score", false, { default: 0 }),
      text("blockers", 8192, false, { default: "[]" }),
      text("evidence", 16384, false, { default: "{}" }),
      text("decidedBy", 254, false),
      text("decisionRationale", 2000, false),
      datetime("createdAt"),
      datetime("decidedAt", false),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "status_idx", type: "key", attributes: ["status"] },
    ],
  },
  {
    id: "executor_registry",
    name: "Verified executor registry",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("name", 96),
      text("provider", 64),
      text("environment", 32, false, { default: "production" }),
      text("status", 32, false, { default: "awaiting_attestation" }),
      text("version", 32),
      text("allowedActions", 4096, false, { default: "[]" }),
      text("attestation", 8192, false, { default: "{}" }),
      text("verifiedBy", 254, false),
      datetime("verifiedAt", false),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_name_unique",
        type: "unique",
        attributes: ["workspaceId", "name"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "telemetry_rollups",
    name: "SLO telemetry rollups",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("sourceType", 64),
      datetime("windowStart"),
      datetime("windowEnd"),
      integer("requestCount", false, { default: 0 }),
      integer("successCount", false, { default: 0 }),
      integer("errorCount", false, { default: 0 }),
      integer("p50LatencyMs", false, { default: 0 }),
      integer("p95LatencyMs", false, { default: 0 }),
      integer("p99LatencyMs", false, { default: 0 }),
      integer("availabilityBps", false, { default: 0 }),
      integer("costCents", false, { default: 0 }),
      text("evidence", 8192, false, { default: "{}" }),
      datetime("createdAt"),
    ],
    indexes: [
      {
        key: "workspace_window_idx",
        type: "key",
        attributes: ["workspaceId", "windowEnd"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_source_idx",
        type: "key",
        attributes: ["workspaceId", "sourceType"],
      },
    ],
  },
  {
    id: "incident_exercises",
    name: "Incident response exercises",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("kind", 64),
      text("status", 32),
      text("severity", 32),
      text("scenario", 255),
      integer("detectionSeconds", false, { default: 0 }),
      integer("mitigationSeconds", false, { default: 0 }),
      integer("externalImpact", false, { default: 0 }),
      text("evidence", 8192, false, { default: "{}" }),
      text("initiatedBy", 254),
      datetime("startedAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_started_idx",
        type: "key",
        attributes: ["workspaceId", "startedAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "billing_controls",
    name: "Billing safeguards",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("status", 32, false, { default: "internal_meter_enforced" }),
      text("currency", 8, false, { default: "USD" }),
      integer("monthlyBudgetCents"),
      integer("warningPercent", false, { default: 70 }),
      integer("hardStopPercent", false, { default: 100 }),
      integer("currentUsageCents", false, { default: 0 }),
      text("config", 8192, false, { default: "{}" }),
      text("updatedBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "status_idx", type: "key", attributes: ["status"] },
    ],
  },
  {
    id: "support_cases",
    name: "Customer support cases",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("source", 64),
      text("subject", 255),
      text("description", 4000),
      text("priority", 32),
      text("status", 32),
      text("customerEmail", 254, false),
      integer("customerNotified", false, { default: 0 }),
      text("ownerEmail", 254),
      datetime("slaDueAt"),
      datetime("resolvedAt", false),
      text("evidence", 8192, false, { default: "{}" }),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
    ],
  },
  {
    id: "scale_gates",
    name: "Scale expansion gates",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("status", 32, false, { default: "assessing" }),
      text("recommendation", 32, false, { default: "hold" }),
      integer("score", false, { default: 0 }),
      integer("expansionAuthorized", false, { default: 0 }),
      text("evidence", 16384, false, { default: "{}" }),
      text("blockers", 8192, false, { default: "[]" }),
      text("decidedBy", 254, false),
      text("decisionRationale", 2000, false),
      datetime("createdAt"),
      datetime("updatedAt"),
      datetime("decidedAt", false),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "status_idx", type: "key", attributes: ["status"] },
    ],
  },
  {
    id: "regional_cells",
    name: "Regional deployment cells",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("code", 32),
      text("name", 96),
      text("role", 32),
      text("status", 32),
      integer("trafficPercent", false, { default: 0 }),
      integer("deploymentVerified", false, { default: 0 }),
      text("dataResidency", 64),
      text("provider", 64),
      text("verification", 8192, false, { default: "{}" }),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_code_unique",
        type: "unique",
        attributes: ["workspaceId", "code"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "provider_routes",
    name: "Provider redundancy routes",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("capability", 64),
      text("provider", 64),
      text("role", 32),
      text("status", 32),
      integer("trafficPercent", false, { default: 0 }),
      text("health", 32),
      text("configuration", 8192, false, { default: "{}" }),
      datetime("verifiedAt", false),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_route_unique",
        type: "unique",
        attributes: ["workspaceId", "capability", "provider"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "failover_drills",
    name: "Regional failover drills",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("kind", 64),
      text("status", 32),
      text("sourceRegion", 32),
      text("targetRegion", 32),
      integer("trafficShifted", false, { default: 0 }),
      integer("dataRestored", false, { default: 0 }),
      integer("observedRtoSeconds", false, { default: 0 }),
      text("evidence", 8192, false, { default: "{}" }),
      text("initiatedBy", 254),
      datetime("startedAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_started_idx",
        type: "key",
        attributes: ["workspaceId", "startedAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "evaluation_runs",
    name: "Continuous evaluation runs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("suite", 64),
      text("status", 32),
      integer("score", false, { default: 0 }),
      integer("cases", false, { default: 0 }),
      integer("passed", false, { default: 0 }),
      integer("failed", false, { default: 0 }),
      text("modelProvider", 64),
      integer("liveModelCalled", false, { default: 0 }),
      text("evidence", 16384, false, { default: "{}" }),
      text("initiatedBy", 254),
      datetime("startedAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_started_idx",
        type: "key",
        attributes: ["workspaceId", "startedAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_suite_idx",
        type: "key",
        attributes: ["workspaceId", "suite"],
      },
    ],
  },
  {
    id: "service_health_updates",
    name: "Service health updates",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("status", 32),
      text("audience", 32),
      text("title", 255),
      text("summary", 4000),
      text("components", 4096, false, { default: "[]" }),
      integer("customerVisible", false, { default: 0 }),
      datetime("publishedAt", false),
      text("createdBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "compliance_automations",
    name: "Compliance automation runs",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("framework", 64),
      text("status", 32),
      text("scope", 255),
      integer("controlCount", false, { default: 0 }),
      integer("evidenceCount", false, { default: 0 }),
      integer("externalSubmitted", false, { default: 0 }),
      text("output", 16384, false, { default: "{}" }),
      text("requestedBy", 254),
      datetime("createdAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "regional_rollout_gates",
    name: "Regional rollout gates",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("status", 32, false, { default: "assessing" }),
      text("recommendation", 32, false, { default: "hold" }),
      integer("score", false, { default: 0 }),
      integer("rolloutAuthorized", false, { default: 0 }),
      text("evidence", 16384, false, { default: "{}" }),
      text("blockers", 8192, false, { default: "[]" }),
      text("decidedBy", 254, false),
      text("decisionRationale", 2000, false),
      datetime("createdAt"),
      datetime("updatedAt"),
      datetime("decidedAt", false),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "status_idx", type: "key", attributes: ["status"] },
    ],
  },
  {
    id: "feedback_cycles",
    name: "Production feedback cycles",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("period", 32),
      text("status", 32),
      text("source", 64),
      integer("signalsCount", false, { default: 0 }),
      integer("productionSignals", false, { default: 0 }),
      integer("verifiedSignals", false, { default: 0 }),
      integer("acceptanceRateBps", false, { default: 0 }),
      integer("medianApprovalMinutes", false, { default: 0 }),
      datetime("sampleWindowStart"),
      datetime("sampleWindowEnd"),
      text("evidence", 16384, false, { default: "{}" }),
      datetime("createdAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_period_idx",
        type: "key",
        attributes: ["workspaceId", "period"],
      },
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
    ],
  },
  {
    id: "tenant_evaluations",
    name: "Tenant-level evaluations",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("suite", 64),
      text("status", 32),
      text("scope", 64),
      integer("score", false, { default: 0 }),
      integer("cases", false, { default: 0 }),
      integer("passed", false, { default: 0 }),
      integer("failed", false, { default: 0 }),
      integer("liveModelCalled", false, { default: 0 }),
      integer("customerDataUsed", false, { default: 0 }),
      text("evidence", 16384, false, { default: "{}" }),
      text("initiatedBy", 254),
      datetime("startedAt"),
      datetime("completedAt", false),
    ],
    indexes: [
      {
        key: "workspace_started_idx",
        type: "key",
        attributes: ["workspaceId", "startedAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_suite_idx",
        type: "key",
        attributes: ["workspaceId", "suite"],
      },
    ],
  },
  {
    id: "autonomy_profiles",
    name: "Workspace autonomy profiles",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("currentTier", 32),
      text("recommendedTier", 32),
      text("status", 32),
      text("maxActionRisk", 32),
      integer("autoExecuteEnabled", false, { default: 0 }),
      integer("score", false, { default: 0 }),
      text("evidence", 16384, false, { default: "{}" }),
      text("blockers", 8192, false, { default: "[]" }),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      { key: "workspace_unique", type: "unique", attributes: ["workspaceId"] },
      { key: "status_idx", type: "key", attributes: ["status"] },
    ],
  },
  {
    id: "workload_forecasts",
    name: "Workspace workload forecasts",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      integer("horizonDays"),
      text("status", 32),
      text("basis", 64),
      integer("observedRuns", false, { default: 0 }),
      integer("predictedRuns", false, { default: 0 }),
      integer("peakConcurrent", false, { default: 0 }),
      integer("confidenceBps", false, { default: 0 }),
      text("dataQuality", 32),
      text("evidence", 16384, false, { default: "{}" }),
      datetime("createdAt"),
    ],
    indexes: [
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "customer_outcomes",
    name: "Customer outcome evidence",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("title", 180),
      text("metric", 96),
      integer("baselineValue"),
      integer("currentValue"),
      text("unit", 32),
      text("status", 32),
      integer("verified", false, { default: 0 }),
      integer("externalVerified", false, { default: 0 }),
      text("source", 64),
      text("evidence", 8192, false, { default: "{}" }),
      text("createdBy", 254),
      datetime("createdAt"),
      datetime("verifiedAt", false),
    ],
    indexes: [
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "policy_recommendations",
    name: "Adaptive policy recommendations",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("title", 180),
      text("status", 32),
      text("sourcePolicy", 128),
      text("proposedPolicy", 16384),
      integer("confidenceBps", false, { default: 0 }),
      text("expectedImpact", 2000),
      integer("autoApplied", false, { default: 0 }),
      text("evidence", 8192, false, { default: "{}" }),
      text("createdBy", 254),
      datetime("createdAt"),
      datetime("updatedAt"),
    ],
    indexes: [
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
      {
        key: "workspace_status_idx",
        type: "key",
        attributes: ["workspaceId", "status"],
      },
    ],
  },
  {
    id: "autonomy_decisions",
    name: "Autonomy tier decisions",
    rowSecurity: true,
    columns: [
      text("workspaceId", 36),
      text("profileId", 36),
      text("decision", 32),
      text("fromTier", 32),
      text("toTier", 32),
      text("rationale", 2000),
      text("evidence", 8192, false, { default: "{}" }),
      integer("enacted", false, { default: 0 }),
      integer("externalActionsChanged", false, { default: 0 }),
      text("decidedBy", 254),
      datetime("createdAt"),
    ],
    indexes: [
      {
        key: "workspace_created_idx",
        type: "key",
        attributes: ["workspaceId", "createdAt"],
        orders: ["ASC", "DESC"],
      },
      { key: "profile_idx", type: "key", attributes: ["profileId"] },
    ],
  },
];

export const buckets = [
  {
    id: "workspace-uploads",
    name: "Workspace uploads",
    fileSecurity: true,
    maximumFileSize: 50 * 1024 * 1024,
    allowedFileExtensions: [
      "pdf", "docx", "txt", "csv", "json", "log", "yaml", "yml",
      "tf", "js", "jsx", "ts", "tsx", "py", "go", "java", "rb",
      "php", "sh", "xml", "toml", "ini", "conf", "png", "jpg", "jpeg",
    ],
  },
  {
    id: "run-evidence",
    name: "Run evidence",
    fileSecurity: true,
    maximumFileSize: 100 * 1024 * 1024,
    allowedFileExtensions: ["json", "txt", "log", "png", "jpg", "jpeg", "pdf"],
  },
  {
    id: "exports",
    name: "Generated exports",
    fileSecurity: true,
    maximumFileSize: 250 * 1024 * 1024,
    allowedFileExtensions: ["csv", "json", "pdf", "zip"],
  },
];

export const functionDefinition = {
  id: "orchestrator",
  name: "Orkestria Orchestrator",
  runtime: "node-22",
  entrypoint: "src/main.js",
  commands: "npm install",
  timeout: 120,
  scopes: [
    "databases.read",
    "databases.write",
    "rows.read",
    "rows.write",
    "buckets.read",
    "buckets.write",
    "files.read",
    "files.write",
  ],
};
